DROP TABLE cliente CASCADE CONSTRAINT;
DROP TABLE ordem_de_compra CASCADE CONSTRAINT;
DROP TABLE funcionario CASCADE CONSTRAINT;
DROP TABLE produto CASCADE CONSTRAINT;
DROP TABLE filial CASCADE CONSTRAINT;
DROP TABLE marca CASCADE CONSTRAINT;
DROP TABLE categoria CASCADE CONSTRAINT;
DROP TABLE caixa CASCADE CONSTRAINT;
