DROP TABLE cliente CASCADE CONSTRAINT;
DROP TABLE ordem_de_compra CASCADE CONSTRAINT;
DROP TABLE funcionario CASCADE CONSTRAINT;
DROP TABLE produto CASCADE CONSTRAINT;
DROP TABLE filial CASCADE CONSTRAINT;
DROP TABLE marca CASCADE CONSTRAINT;
DROP TABLE categoria CASCADE CONSTRAINT;
DROP TABLE caixa CASCADE CONSTRAINT;

DROP TABLE dependente CASCADE CONSTRAINT;
DROP TABLE fornecedor CASCADE CONSTRAINT;
DROP TABLE equipamento CASCADE CONSTRAINT;
DROP TABLE nota_fiscal CASCADE CONSTRAINT;
DROP TABLE solicitacao CASCADE CONSTRAINT;
DROP TABLE item CASCADE CONSTRAINT;

DROP TABLE telefone_cliente CASCADE CONSTRAINT;
DROP TABLE telefone_funcionario CASCADE CONSTRAINT;
DROP TABLE telefone_fornecedor  CASCADE CONSTRAINT;

DROP TABLE realiza_reclamacao CASCADE CONSTRAINT;
DROP TABLE realiza_manutencao  CASCADE CONSTRAINT;
